#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mycv-deployment
spec:
  selector:
    matchLabels:
      app: api-mycv-server
  replicas: 1
  template:
    metadata:
      labels:
        app: api-mycv-server
    spec:
      containers:
      - name: api-mycv-container
        image: docker.io/alegxmx/api-cv:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: api-mycv-server
  name: api-mycv-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: api-mycv-server
  type: LoadBalancer
